name: Security Scan (reusable)
on:
  workflow_call:
    inputs:
      docker-images:
        description: 'JSON array'
        type: string
        default: '[]'
      gitleaks-only:
        description: 'Only gitleaks'
        type: boolean
        default: false
      osv-scan-args:
        description: 'OSV args'
        type: string
        default: |-
          --recursive
          ./
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "docker=${{ inputs.docker-images }}"
